(function(){
"use strict";
const db=window.bakerySupabase;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=window.escapeHtml||((v)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])));
const q=v=>Number(v)||0, qty=v=>(window.qty?window.qty(v):new Intl.NumberFormat("en-US",{maximumFractionDigits:4}).format(q(v))), money=v=>new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(q(v)), today=()=>new Date().toISOString().slice(0,10);
const val=id=>document.getElementById(id)?.value??"", checked=id=>!!document.getElementById(id)?.checked;
let page="dashboard",lang=localStorage.getItem("bakery_lang")||"my";
let items=[],purchases=[],recipes=[],recipeLines=[],orders=[],orderLines=[],operations=[],sales=[],saleLines=[];
const T={en:{dashboard:"Dashboard",items:"Item Dashboard",purchases:"Purchase",recipes:"Recipe",orders:"Order",production:"Production",packaging:"Packaging",sales:"Sale",reports:"Reports",more:"More",addItem:"+ Add Item",addPurchase:"+ Add Purchase",addRecipe:"+ Add Recipe",addOrder:"+ Add Order",addSale:"+ Add Sale",refresh:"Refresh",signIn:"Sign in",authRequired:"Supabase Auth account required.",save:"Save",cancel:"Cancel",total:"Total",active:"Active",confirmed:"Confirmed",saleEnabled:"Sale Enabled",productionEnabled:"Production Enabled",packagingEnabled:"Packaging Enabled",purchaseValue:"Purchase Value",autoIssue:"Auto Issue",saveRow:"Save Row",noRecords:"No records yet.",issued:"Issued",returned:"Return",used:"Used",damage:"Damage",closing:"Closing",open:"Open",edit:"Edit",export:"Export CSV",import:"Import CSV",productionSub:"Production table — Issue, Return, Used, Damage, Closing.",packagingSub:"Packaging table — Issue, Return, Used, Damage, Closing.",saleItemsOnly:"Sale-enabled items only",issuedNote:"Issued is calculated from Order + active Recipe; you can edit it manually before Save.",error:"Error"},my:{dashboard:"Dashboard",items:"Item Dashboard",purchases:"Purchase",recipes:"Recipe",orders:"Order",production:"Production",packaging:"Packaging",sales:"Sale",reports:"Reports",more:"More",addItem:"+ Item ထည့်မည်",addPurchase:"+ Purchase ထည့်မည်",addRecipe:"+ Recipe ထည့်မည်",addOrder:"+ Order ထည့်မည်",addSale:"+ Sale ထည့်မည်",refresh:"ပြန်တင်မည်",signIn:"ဝင်မည်",authRequired:"Supabase Auth Account လိုအပ်ပါသည်",save:"သိမ်းမည်",cancel:"ပယ်ဖျက်မည်",total:"စုစုပေါင်း",active:"အသုံးပြုနေ",confirmed:"အတည်ပြု",saleEnabled:"Sale ဖွင့်ထား",productionEnabled:"Production ဖွင့်ထား",packagingEnabled:"Packaging ဖွင့်ထား",purchaseValue:"ဝယ်ယူတန်ဖိုး",autoIssue:"Issue Auto တွက်မည်",saveRow:"Row သိမ်းမည်",noRecords:"မှတ်တမ်းမရှိသေးပါ",issued:"Issued",returned:"Return",used:"Used",damage:"Damage",closing:"Closing",open:"ဖွင့်မည်",edit:"ပြင်မည်",export:"CSV Export",import:"CSV Import",productionSub:"Production Table — Issue, Return, Used, Damage, Closing",packagingSub:"Packaging Table — Issue, Return, Used, Damage, Closing",saleItemsOnly:"Sale ဖွင့်ထားသော Item များသာ",issuedNote:"Issued ကို Order + Active Recipe အတိုင်း Auto တွက်ပေးထားပါသည်။ Save မလုပ်ခင် Manual ပြင်နိုင်ပါသည်။",error:"အမှား"}};
const t=k=>(T[lang]?.[k]||T.en[k]||k);
const status=$("#connectionStatus"),content=$("#content"),dialog=$("#dialog"),form=$("#form"),body=$("#formBody"),title=$("#dialogTitle"),fmsg=$("#formMessage");
function st(x,bad=false){if(status){status.textContent=x;status.className="status "+(bad?"danger-text":"success");}}
function signed(v){$("#authView")?.classList.toggle("hidden",v);$("#mainView")?.classList.toggle("hidden",!v);$("#logoutBtn")?.classList.toggle("hidden",!v);}
function itemName(id){return items.find(x=>String(x.id)===String(id))?.name||"Unknown"}
function unit(id){return items.find(x=>String(x.id)===String(id))?.base_unit||""}
function avg(id){const p=purchases.filter(x=>String(x.item_id)===String(id)&&x.confirmed),b=p.reduce((s,x)=>s+q(x.base_quantity),0),v=p.reduce((s,x)=>s+q(x.total_cost),0);return b?v/b:0}
function close(o){return Math.max(0,q(o.opening_qty)+q(o.in_qty)-q(o.issued_qty)+q(o.return_qty)-q(o.used_qty)-q(o.damage_qty))}
function opts(filter=()=>true,selected=""){return items.filter(x=>x.active&&filter(x)).map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(selected)?"selected":""}>${esc(x.name)} (${esc(x.base_unit)})</option>`).join("")}
function table(h,rows){return `<div class="table-card"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.join(""):`<tr><td colspan="${h.length}" class="empty">${t("noRecords")}</td></tr>`}</tbody></table></div>`}
async function run(p,label){const r=await p;if(r.error)throw new Error((label?label+": ":"")+r.error.message);return r}
async function load(){
 st("Loading…");
 try{
  const names=["items","purchases","recipes","recipe_lines","orders","order_lines","daily_operations","sales","sale_lines"];
  const qs=[
   db.from("items").select("*").order("name"),db.from("purchases").select("*").order("purchase_date",{ascending:false}),
   db.from("recipes").select("*").order("created_at",{ascending:false}),db.from("recipe_lines").select("*"),
   db.from("orders").select("*").order("order_date",{ascending:false}),db.from("order_lines").select("*"),
   db.from("daily_operations").select("*").order("operation_date",{ascending:false}),db.from("sales").select("*").order("sale_date",{ascending:false}),
   db.from("sale_lines").select("*")
  ];
  const rs=await Promise.all(qs);const bad=rs.find(x=>x.error);if(bad)throw new Error(bad.error.message);
  [items,purchases,recipes,recipeLines,orders,orderLines,operations,sales,saleLines]=rs.map(x=>x.data||[]);
  st("Supabase connected");render();
 }catch(e){st("Database error",true);content.innerHTML=`<div class="card"><b>${t("error")}</b><p>${esc(e.message)}</p><button id="retry">${t("refresh")}</button></div>`;$("#retry")?.addEventListener("click",load)}
}
function meta(){return {dashboard:["dashboard",""],items:["items","addItem"],purchases:["purchases","addPurchase"],recipes:["recipes","addRecipe"],orders:["orders","addOrder"],production:["production","autoIssue"],packaging:["packaging","autoIssue"],sales:["sales","addSale"],reports:["reports","refresh"],more:["more",""]}[page]||["dashboard",""]}
function render(){
 const [key,action]=meta();$("#pageTitle").textContent=t(key);$("#pageSub").textContent=page==="production"?t("productionSub"):page==="packaging"?t("packagingSub"):"";
 const p=$("#primaryAction");p.textContent=action?t(action):"";p.classList.toggle("hidden",!action);
 $$("#tabs button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));
 try{({dashboard:dash,items:itemsPage,purchases:purchasePage,recipes:recipePage,orders:orderPage,production:()=>opsPage("production"),packaging:()=>opsPage("packaging"),sales:salesPage,reports:reportsPage,more:morePage}[page]||dash)()}catch(e){content.innerHTML=`<div class="card"><b>${t("error")}</b><p>${esc(e.message)}</p></div>`}
}
function dash(){
 const pv=purchases.filter(x=>x.confirmed).reduce((s,x)=>s+q(x.total_cost),0),sv=sales.reduce((s,x)=>s+q(x.total_amount),0),uv=operations.reduce((s,x)=>s+q(x.used_qty)*avg(x.item_id),0),dv=operations.reduce((s,x)=>s+q(x.damage_qty)*avg(x.item_id),0);
 content.innerHTML=`<div class="kpi-grid"><div class="kpi-card"><strong>${money(pv)}</strong><span>Purchase</span></div><div class="kpi-card"><strong>${money(sv)}</strong><span>Sale</span></div><div class="kpi-card"><strong>${money(uv)}</strong><span>Used</span></div><div class="kpi-card"><strong>${money(dv)}</strong><span>Damage</span></div></div><div class="report-grid" style="margin-top:12px"><div class="card"><h3>Production</h3>${operations.filter(x=>x.operation_type==="production").length} rows</div><div class="card"><h3>Packaging</h3>${operations.filter(x=>x.operation_type==="packaging").length} rows</div></div>`;
}
function bar(extra=""){return `<div class="toolbar"><input id="search" placeholder="ရှာရန်…">${extra}<button id="reload">${t("refresh")}</button></div>`}
function itemsPage(){
 content.innerHTML=`<div class="stats"><div class="stat"><strong>${items.length}</strong><span>${t("total")}</span></div><div class="stat"><strong>${items.filter(x=>x.active).length}</strong><span>${t("active")}</span></div><div class="stat"><strong>${items.filter(x=>x.sale_enabled&&x.active).length}</strong><span>${t("saleEnabled")}</span></div><div class="stat"><strong>${items.filter(x=>x.production_enabled&&x.active).length}/${items.filter(x=>x.packaging_enabled&&x.active).length}</strong><span>Prod / Pack</span></div></div>${bar(`<button id="exp">${t("export")}</button><button id="imp">${t("import")}</button>`)}<div id="tbl"></div>`;
 const draw=()=>{const s=val("search").toLowerCase(),a=items.filter(x=>[x.name,x.code,x.category].some(v=>String(v||"").toLowerCase().includes(s)));$("#tbl").innerHTML=table(["Item","Code","Category","Unit","Flags","Status","Action"],a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.code||"")}</td><td>${esc(x.category||"")}</td><td>${esc(x.purchase_unit)} → ${esc(x.base_unit)} ×${qty(x.unit_factor_to_base)}</td><td><span class="badge ${x.sale_enabled?"on":"off"}">Sale</span><span class="badge ${x.production_enabled?"on":"off"}">Prod</span><span class="badge ${x.packaging_enabled?"on":"off"}">Pack</span></td><td>${x.active?"Active":"Inactive"}</td><td><button data-edit="${esc(x.id)}"> ${t("edit")} </button></td></tr>`))};draw();$("#search").oninput=draw;$("#reload").onclick=load;$("#exp").onclick=()=>csv("items.csv",items);$("#imp").onclick=importItems;
}
function purchasePage(){
 content.innerHTML=`${bar(`<button id="exp">${t("export")}</button>`)}<div id="tbl"></div>`;const draw=()=>$("#tbl").innerHTML=table(["Date","Item","Qty","Base Qty","Total","Cost/Base","Supplier","Status","Action"],purchases.map(x=>`<tr><td>${esc(x.purchase_date)}</td><td>${esc(itemName(x.item_id))}</td><td>${qty(x.quantity)} ${esc(x.purchase_unit)}</td><td>${qty(x.base_quantity)} ${esc(unit(x.item_id))}</td><td>${money(x.total_cost)}</td><td>${money(x.cost_per_base_unit)}</td><td>${esc(x.supplier||"")}</td><td>${x.confirmed?"Confirmed":"Draft"}</td><td>${x.confirmed?"—":`<button data-confirm="${esc(x.id)}">Confirm</button>`}</td></tr>`));draw();$("#reload").onclick=load;$("#exp").onclick=()=>csv("purchases.csv",purchases)}
function recipePage(){content.innerHTML=`${bar()}<div id="tbl"></div>`;$("#tbl").innerHTML=table(["Output","Type","Version","Components","Status","Action"],recipes.map(r=>`<tr><td>${esc(itemName(r.item_id))}</td><td>${esc(r.recipe_type)}</td><td>${r.version}</td><td>${recipeLines.filter(x=>String(x.recipe_id)===String(r.id)).length}</td><td>${r.active?"Active":"Inactive"}</td><td><button data-recipe="${esc(r.id)}">${t("edit")}</button></td></tr>`));$("#reload").onclick=load}
function orderPage(){content.innerHTML=`${bar()}<div id="tbl"></div>`;$("#tbl").innerHTML=table(["Date","Order No","Status","Items","Action"],orders.map(o=>`<tr><td>${esc(o.order_date)}</td><td>${esc(o.order_no||"")}</td><td>${esc(o.status)}</td><td>${orderLines.filter(l=>String(l.order_id)===String(o.id)).map(l=>`${esc(itemName(l.item_id))} × ${qty(l.quantity)}`).join("<br>")}</td><td>${o.status==="pending"?`<button data-issue="${esc(o.id)}">Issue</button>`:"—"}</td></tr>`));$("#reload").onclick=load}
function autoIssue(type,date,itemId){let total=0;for(const o of orders.filter(x=>x.order_date===date&&x.status!=="cancelled"))for(const l of orderLines.filter(z=>String(z.order_id)===String(o.id))){const out=items.find(i=>String(i.id)===String(l.item_id));if(!out)continue;for(const r of recipes.filter(r=>String(r.item_id)===String(out.id)&&r.active&&r.recipe_type===type))for(const c of recipeLines.filter(c=>String(c.recipe_id)===String(r.id)&&String(c.component_item_id)===String(itemId)))total+=q(l.quantity)*q(c.qty_per_output)}return total}
function opsPage(type){
 content.innerHTML=`<div class="note">${t("issuedNote")}</div><div class="toolbar"><input id="odate" type="date" value="${today()}"><button id="auto">${t("autoIssue")}</button><button id="exp">${t("export")}</button><button id="imp">${t("import")}</button><button id="reload">${t("refresh")}</button></div><div id="tbl"></div>`;
 const draw=()=>{const d=val("odate")||today(),rows=operations.filter(x=>x.operation_type===type&&x.operation_date===d),m=new Map(rows.map(x=>[String(x.item_id),x]));items.filter(i=>i.active&&(type==="production"?i.production_enabled:i.packaging_enabled)).forEach(i=>{if(!m.has(String(i.id)))m.set(String(i.id),{item_id:i.id,operation_date:d,operation_type:type,opening_qty:0,in_qty:0,issued_qty:autoIssue(type,d,i.id),return_qty:0,used_qty:0,damage_qty:0,closing_qty:0,used_manual:false})});$("#tbl").innerHTML=table(["Date","Item","Opening","In","Issued","Return","Used","Damage","Closing","Mode","Action"],[...m.values()].map(x=>`<tr data-row data-item="${esc(x.item_id)}"><td>${esc(x.operation_date)}</td><td>${esc(itemName(x.item_id))}</td>${["opening_qty","in_qty","issued_qty","return_qty","used_qty","damage_qty"].map(k=>`<td><input data-k="${k}" type="number" min="0" step="0.000001" value="${q(x[k])}"></td>`).join("")}<td class="cc">${qty(close(x))}</td><td>${x.used_manual?"Manual":"Auto"}</td><td><button data-saveop data-item="${esc(x.item_id)}">${t("saveRow")}</button></td></tr>`));$$("[data-row]").forEach(tr=>$$("input",tr).forEach(i=>i.oninput=()=>{const o={};$$("input",tr).forEach(z=>o[z.dataset.k]=q(z.value));$(".cc",tr).textContent=qty(close(o))}));};
 draw();$("#odate").onchange=draw;$("#reload").onclick=load;$("#auto").onclick=()=>autoCurrent(type,val("odate")||today());$("#exp").onclick=()=>csv(type+".csv",operations.filter(x=>x.operation_type===type));$("#imp").onclick=()=>importOps(type);
}
async function autoCurrent(type,date){try{for(const i of items.filter(x=>x.active)){const a=autoIssue(type,date,i.id);if(a<=0)continue;const e=operations.find(x=>x.operation_date===date&&String(x.item_id)===String(i.id)&&x.operation_type===type);await run(db.from("daily_operations").upsert({operation_date:date,item_id:i.id,operation_type:type,opening_qty:q(e?.opening_qty),in_qty:q(e?.in_qty),issued_qty:a,return_qty:q(e?.return_qty),used_qty:q(e?.used_qty),damage_qty:q(e?.damage_qty),closing_qty:close({opening_qty:q(e?.opening_qty),in_qty:q(e?.in_qty),issued_qty:a,return_qty:q(e?.return_qty),used_qty:q(e?.used_qty),damage_qty:q(e?.damage_qty)}),used_manual:false},{onConflict:"operation_date,item_id,operation_type"}),"Auto Issue")}await load()}catch(e){alert(e.message)}}
function salesPage(){content.innerHTML=`${bar()}<div id="tbl"></div>`;$("#tbl").innerHTML=table(["Date","Shop","Items","Total","Action"],sales.map(s=>`<tr><td>${esc(s.sale_date)}</td><td>${esc(s.shop_name||"")}</td><td>${saleLines.filter(l=>String(l.sale_id)===String(s.id)).map(l=>`${esc(itemName(l.item_id))} × ${qty(l.quantity)} @ ${money(l.unit_price)}`).join("<br>")}</td><td>${money(s.total_amount)}</td><td><button data-sale="${esc(s.id)}">${t("edit")}</button></td></tr>`));$("#reload").onclick=load}
function reportsPage(){const pv=purchases.filter(x=>x.confirmed).reduce((s,x)=>s+q(x.total_cost),0),sv=sales.reduce((s,x)=>s+q(x.total_amount),0);content.innerHTML=`<div class="kpi-grid"><div class="kpi-card"><strong>${money(pv)}</strong><span>Purchase</span></div><div class="kpi-card"><strong>${money(sv)}</strong><span>Sale</span></div></div>${bar()}<div id="tbl"></div>`;$("#tbl").innerHTML=table(["Item","Avg Cost","Used","Damage","Closing"],items.map(i=>{const a=avg(i.id),o=operations.filter(x=>String(x.item_id)===String(i.id));return `<tr><td>${esc(i.name)}</td><td>${money(a)}</td><td>${qty(o.reduce((s,x)=>s+q(x.used_qty),0))}</td><td>${qty(o.reduce((s,x)=>s+q(x.damage_qty),0))}</td><td>${qty(o.reduce((s,x)=>s+q(x.closing_qty),0))}</td></tr>`}));$("#reload").onclick=load}
function morePage(){content.innerHTML=`<div class="more-grid">${[["items","items"],["production","production"],["packaging","packaging"],["sales","sales"],["reports","reports"]].map(([k,p])=>`<div class="more-card"><h3>${t(k)}</h3><button data-goto="${p}">${t("open")}</button></div>`).join("")}</div>`}
function openDialog(tt,html,save){title.textContent=tt;body.innerHTML=html;fmsg.textContent="";form.onsubmit=async e=>{e.preventDefault();try{await save()}catch(x){fmsg.textContent=x.message;fmsg.className="message error"}};dialog.showModal()}
function itemForm(id){
 const x=id?items.find(i=>String(i.id)===String(id)):null;
 openDialog(id?"Edit Item":t("addItem"),`<div class="form-grid"><label>Name*<input id="n" required value="${esc(x?.name||"")}"></label><label>Code<input id="c" value="${esc(x?.code||"")}"></label><label>Category<input id="cat" value="${esc(x?.category||"")}"></label><label>Base Unit<select id="bu"><option value="g" ${x?.base_unit==="g"?"selected":""}>g</option><option value="pcs" ${x?.base_unit==="pcs"?"selected":""}>pcs</option></select></label><label>Purchase Unit<select id="pu">${["g","kg","pcs","box","pack"].map(u=>`<option ${x?.purchase_unit===u?"selected":""}>${u}</option>`).join("")}</select></label><label>Factor<input id="fac" type="number" step="0.000001" value="${x?.unit_factor_to_base||1}"></label></div><div class="checks"><label><input id="sale" type="checkbox" ${x?.sale_enabled?"checked":""}> Sale</label><label><input id="prod" type="checkbox" ${x?.production_enabled?"checked":""}> Production</label><label><input id="pack" type="checkbox" ${x?.packaging_enabled?"checked":""}> Packaging</label><label><input id="act" type="checkbox" ${x?x.active?"checked":"":"checked"}> Active</label></div>`,async()=>{const p={name:val("n").trim(),code:val("c").trim()||null,category:val("cat").trim()||null,base_unit:val("bu"),purchase_unit:val("pu"),unit_factor_to_base:q(val("fac"))||1,sale_enabled:checked("sale"),production_enabled:checked("prod"),packaging_enabled:checked("pack"),active:checked("act"),updated_at:new Date().toISOString()};if(!p.name)throw new Error("Item name required");await run(id?db.from("items").update(p).eq("id",id):db.from("items").insert(p),"Save item");dialog.close();load()})
}
function purchaseForm(){openDialog(t("addPurchase"),`<div class="form-grid"><label>Date<input id="pd" type="date" value="${today()}"></label><label>Item<select id="pi">${opts()}</select></label><label>Qty<input id="pq" type="number" step="0.000001"></label><label>Unit<select id="pu"><option>kg</option><option>g</option><option>pcs</option><option>box</option><option>pack</option></select></label><label>Total Cost<input id="pc" type="number" step="0.01"></label><label>Supplier<input id="ps"></label></div>`,async()=>{const it=items.find(i=>String(i.id)===String(val("pi"))),u=val("pu"),f=!it?null:(u===it.base_unit?1:(u==="kg"&&it.base_unit==="g"?1000:(u==="box"||u==="pack")&&it.base_unit==="pcs"?q(it.unit_factor_to_base):null));if(!it||!f||q(val("pq"))<=0)throw new Error("Invalid item/unit");const b=q(val("pq"))*f,c=q(val("pc"));await run(db.from("purchases").insert({purchase_date:val("pd")||today(),item_id:it.id,quantity:q(val("pq")),purchase_unit:u,base_quantity:b,total_cost:c,cost_per_base_unit:c/b,supplier:val("ps").trim()||null,created_by:(await db.auth.getUser()).data.user?.id||null}),"Save purchase");dialog.close();load()})}
function recipeForm(id){
 const r=id?recipes.find(x=>String(x.id)===String(id)):null,ls=r?recipeLines.filter(x=>String(x.recipe_id)===String(id)):[];
 openDialog(id?"Edit Recipe":t("addRecipe"),`<div class="form-grid"><label>Output<select id="ri">${opts(x=>x.production_enabled||x.packaging_enabled,r?.item_id)}</select></label><label>Type<select id="rt"><option value="production" ${r?.recipe_type==="production"?"selected":""}>production</option><option value="packaging" ${r?.recipe_type==="packaging"?"selected":""}>packaging</option></select></label></div><div id="comps">${ls.map(l=>`<div class="grid3 comp"><select class="ci">${opts(x=>String(x.id)!==String(r?.item_id),l.component_item_id)}</select><input class="cq" type="number" step="0.000001" value="${q(l.qty_per_output)}"><button type="button" class="rm">Remove</button></div>`).join("")}</div><button type="button" id="addc">+ Component</button>`,async()=>{const p={item_id:val("ri"),recipe_type:val("rt"),version:q(r?.version)||1,active:true};const rr=await run(id?db.from("recipes").update(p).eq("id",id).select().single():db.from("recipes").insert(p).select().single(),"Save recipe");const rid=rr.data.id;if(id)await run(db.from("recipe_lines").delete().eq("recipe_id",rid),"Delete recipe lines");const rows=$$(".comp").map(c=>({recipe_id:rid,component_item_id:$(".ci",c)?.value,qty_per_output:q($(".cq",c)?.value)})).filter(x=>x.component_item_id&&x.qty_per_output>0);if(rows.length)await run(db.from("recipe_lines").insert(rows),"Save recipe lines");dialog.close();load()});
 setTimeout(()=>{function bind(){$$(".rm").forEach(b=>b.onclick=()=>b.parentElement.remove())}$("#addc").onclick=()=>{$("#comps").insertAdjacentHTML("beforeend",`<div class="grid3 comp"><select class="ci">${opts()}</select><input class="cq" type="number" step="0.000001"><button type="button" class="rm">Remove</button></div>`);bind()};bind()},0)
}
function orderForm(){const si=items.filter(x=>x.active&&x.sale_enabled);openDialog(t("addOrder"),`<label>Date<input id="od" type="date" value="${today()}"></label><label>Order No<input id="on"></label><div id="ol"></div><button type="button" id="addol">+ Item</button>`,async()=>{const rr=await run(db.from("orders").insert({order_date:val("od")||today(),order_no:val("on").trim()||null,created_by:(await db.auth.getUser()).data.user?.id||null}).select().single(),"Save order");const rows=$$(".oline").map(x=>({order_id:rr.data.id,item_id:$("select",x)?.value,quantity:q($("input",x)?.value)})).filter(x=>x.item_id&&x.quantity>0);if(!rows.length){await db.from("orders").delete().eq("id",rr.data.id);throw new Error("Add item");}await run(db.from("order_lines").insert(rows),"Save order lines");dialog.close();load()});setTimeout(()=>{$("#addol").onclick=()=>$("#ol").insertAdjacentHTML("beforeend",`<div class="grid2 oline"><select>${si.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}</select><input type="number" step="0.000001"></div>`);$("#addol").click()},0)}
async function issue(id){try{const o=orders.find(x=>String(x.id)===String(id));for(const l of orderLines.filter(x=>String(x.order_id)===String(id))){const out=items.find(x=>String(x.id)===String(l.item_id));if(!out)continue;for(const type of ["production","packaging"]){if(!(type==="production"?out.production_enabled:out.packaging_enabled))continue;const r=recipes.find(x=>String(x.item_id)===String(out.id)&&x.active&&x.recipe_type===type);if(!r)continue;for(const c of recipeLines.filter(x=>String(x.recipe_id)===String(r.id))){const old=operations.find(x=>x.operation_date===o.order_date&&String(x.item_id)===String(c.component_item_id)&&x.operation_type===type),issued=q(old?.issued_qty)+q(c.qty_per_output)*q(l.quantity);await run(db.from("daily_operations").upsert({operation_date:o.order_date,item_id:c.component_item_id,operation_type:type,opening_qty:q(old?.opening_qty),in_qty:q(old?.in_qty),issued_qty:issued,return_qty:q(old?.return_qty),used_qty:q(old?.used_qty),damage_qty:q(old?.damage_qty),closing_qty:close({opening_qty:q(old?.opening_qty),in_qty:q(old?.in_qty),issued_qty:issued,return_qty:q(old?.return_qty),used_qty:q(old?.used_qty),damage_qty:q(old?.damage_qty)}),used_manual:false},{onConflict:"operation_date,item_id,operation_type"}),"Issue")}}}await run(db.from("orders").update({status:"issued"}).eq("id",id),"Update order");load()}catch(e){alert(e.message)}}
function saleForm(id){const s=id?sales.find(x=>String(x.id)===String(id)):null,ls=s?saleLines.filter(x=>String(x.sale_id)===String(id)):[];openDialog(id?"Edit Sale":t("addSale"),`<label>Date<input id="sd" type="date" value="${esc(s?.sale_date||today())}"></label><label>Shop<input id="shop" value="${esc(s?.shop_name||"")}"></label><div id="sl">${ls.map(l=>`<div class="grid3 sline"><select>${items.filter(x=>x.active&&x.sale_enabled).map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(l.item_id)?"selected":""}>${esc(x.name)}</option>`).join("")}</select><input class="sq" type="number" step="0.000001" value="${q(l.quantity)}"><input class="sp" type="number" step="0.01" value="${q(l.unit_price)}"></div>`).join("")}</div><button type="button" id="addsl">+ Item</button>`,async()=>{let sid=s?.id;if(sid){await run(db.from("sale_lines").delete().eq("sale_id",sid),"Delete lines");await run(db.from("sales").update({sale_date:val("sd"),shop_name:val("shop"),total_amount:0}).eq("id",sid),"Update sale")}else{const rr=await run(db.from("sales").insert({sale_date:val("sd")||today(),shop_name:val("shop").trim()||null,total_amount:0,created_by:(await db.auth.getUser()).data.user?.id||null}).select().single(),"Create sale");sid=rr.data.id}const rows=$$(".sline").map(x=>({sale_id:sid,item_id:$("select",x)?.value,quantity:q($(".sq",x)?.value),unit_price:q($(".sp",x)?.value)})).filter(x=>x.item_id&&x.quantity>0);if(!rows.length)throw new Error("Add sale item");await run(db.from("sale_lines").insert(rows),"Save sale lines");await run(db.from("sales").update({total_amount:rows.reduce((s,x)=>s+x.quantity*x.unit_price,0)}).eq("id",sid),"Update total");dialog.close();load()});setTimeout(()=>{$("#addsl").onclick=()=>$("#sl").insertAdjacentHTML("beforeend",`<div class="grid3 sline"><select>${items.filter(x=>x.active&&x.sale_enabled).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}</select><input class="sq" type="number" step="0.000001"><input class="sp" type="number" step="0.01"></div>`)},0)}
function csv(name,rows){if(!rows.length)return alert(t("noRecords"));const keys=Object.keys(rows[0]),s="\uFEFF"+[keys.map(x=>`"${x}"`).join(","),...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(","))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function parse(text){text=text.replace(/^\uFEFF/,"");const rows=[];let row=[],f="",qte=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(qte){if(c==='"'&&n==='"'){f+='"';i++}else if(c==='"')qte=false;else f+=c}else if(c==='"')qte=true;else if(c===','){row.push(f);f=""}else if(c==='\n'){row.push(f);rows.push(row);row=[];f=""}else if(c!=='\r')f+=c}if(f||row.length){row.push(f);rows.push(row)}const h=rows.shift()||[];return rows.filter(r=>r.some(x=>x.trim())).map(r=>Object.fromEntries(h.map((x,i)=>[x.trim(),r[i]??""])))}
function file(){return new Promise(res=>{const i=document.createElement("input");i.type="file";i.accept=".csv,text/csv";i.onchange=()=>res(i.files?.[0]);i.click()})}
async function importItems(){const f=await file();if(!f)return;try{for(const r of parse(await f.text())){if(!r.name)continue;await run(db.from("items").upsert({name:r.name,code:r.code||null,category:r.category||null,base_unit:r.base_unit==="g"?"g":"pcs",purchase_unit:r.purchase_unit||"pcs",unit_factor_to_base:q(r.unit_factor_to_base)||1,sale_enabled:/^(1|true|yes)$/i.test(r.sale_enabled),production_enabled:/^(1|true|yes)$/i.test(r.production_enabled),packaging_enabled:/^(1|true|yes)$/i.test(r.packaging_enabled),min_stock:q(r.min_stock),active:!/^(0|false|no)$/i.test(r.active||"true")},{onConflict:"code"}),"Import item")}load()}catch(e){alert(e.message)}}
async function importOps(type){const f=await file();if(!f)return;try{for(const r of parse(await f.text())){const it=items.find(x=>String(x.id)===String(r.item_id)||x.name===r.item);if(!it)continue;await run(db.from("daily_operations").upsert({operation_date:r.date||today(),item_id:it.id,operation_type:type,opening_qty:q(r.opening),in_qty:q(r.in),issued_qty:q(r.issued),return_qty:q(r.return),used_qty:q(r.used),damage_qty:q(r.damage),closing_qty:q(r.closing),used_manual:true},{onConflict:"operation_date,item_id,operation_type"}),"Import operation")}load()}catch(e){alert(e.message)}}
$("#loginForm")?.addEventListener("submit",async e=>{e.preventDefault();const m=$("#authMessage");try{const email=val("email").trim(),password=val("password");if(!email||!password)throw new Error("Email and password are required.");m.textContent="Signing in…";const r=await db.auth.signInWithPassword({email,password});if(r.error)throw r.error;signed(true);await load()}catch(x){if(m)m.textContent=x.message||String(x)}});
$("#logoutBtn")?.addEventListener("click",async()=>{await db.auth.signOut();signed(false);st("Checking…")});
$("#langBtn")?.addEventListener("click",()=>{lang=lang==="my"?"en":"my";localStorage.setItem("bakery_lang",lang);render()});
$("#tabs")?.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b){page=b.dataset.page;render()}});
$("#primaryAction")?.addEventListener("click",()=>({items:()=>itemForm(),purchases:purchaseForm,recipes:()=>recipeForm(),orders:orderForm,production:()=>autoCurrent("production",today()),packaging:()=>autoCurrent("packaging",today()),sales:()=>saleForm(),reports:load}[page]||(()=>{}))());
$("#closeDialog")?.addEventListener("click",()=>dialog.close());$("#cancelDialog")?.addEventListener("click",()=>dialog.close());
content?.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.goto){page=b.dataset.goto;render();return}if(b.dataset.edit){itemForm(b.dataset.edit);return}if(b.dataset.confirm){const p=purchases.find(x=>String(x.id)===String(b.dataset.confirm));if(p){try{await run(db.from("purchases").update({confirmed:true,applied:true}).eq("id",p.id),"Confirm purchase");await load()}catch(x){alert(x.message)}}return}if(b.dataset.recipe){recipeForm(b.dataset.recipe);return}if(b.dataset.issue){issue(b.dataset.issue);return}if(b.dataset.sale){saleForm(b.dataset.sale);return}if(b.dataset.saveop){const tr=b.closest("tr"),n=k=>q($(`[data-k="${k}"]`,tr)?.value);try{await run(db.from("daily_operations").upsert({operation_date:val("odate")||today(),item_id:b.dataset.item,operation_type:page,opening_qty:n("opening_qty"),in_qty:n("in_qty"),issued_qty:n("issued_qty"),return_qty:n("return_qty"),used_qty:n("used_qty"),damage_qty:n("damage_qty"),closing_qty:close({opening_qty:n("opening_qty"),in_qty:n("in_qty"),issued_qty:n("issued_qty"),return_qty:n("return_qty"),used_qty:n("used_qty"),damage_qty:n("damage_qty")}),used_manual:true},{onConflict:"operation_date,item_id,operation_type"}),"Save operation");await load()}catch(x){alert(x.message)}}});
db.auth.onAuthStateChange((_e,s)=>{signed(!!s);if(s)load()});
(async()=>{if(!db){st("Supabase SDK error",true);return}try{const r=await db.auth.getSession();if(r.error)throw r.error;signed(!!r.data.session);if(r.data.session)load();else st("Checking…")}catch(e){st("Auth check failed",true)}})();
})();